"""Tier-3 auxiliary "bridge" layer.

The bridge is a short additive layer mixed over the transition — it **never**
replaces the algorithmic transition. Two sources, behind one seam
(``prepare_clip``: trim -> normalize -> length-match):

  * **Real AI clip** (preferred): a clip generated by **MusicGen-Style** on **Modal**
    (CUDA), conditioned on a reference taken from the A->B boundary (so it inherits
    the key/timbre of the actual transition), written to ``assets/generated/``.
    ``resolve_bridge`` loads it if present.
  * **Procedural stand-in** (fallback, always available): a synthesized genre
    element (riser, hip-hop fill, dub siren, ambient pad, cymbal — see
    ``genre.BRIDGE_SPECS``) so the pipeline runs with no external dependency / GPU.

To produce a real clip the local pipeline writes two conditioning artifacts — a
**boundary reference WAV** (``extract_boundary_reference``) and a **text prompt**
(``build_bridge_prompt``) built from the analysis (BPM, key, duration). With
``--generate`` the pipeline sends those to the Modal app (``infra/modal_bridge.py``,
via ``smartautodj.remote``) and mixes the result in one command; otherwise generate
manually with ``modal run`` (or the legacy Colab notebook) and drop the clip in
``assets/generated/``, then re-run tier 3 to pick it up.
"""

from __future__ import annotations

import os

import numpy as np
from scipy.signal import butter, sosfiltfilt

from . import DEFAULT_SR
from .io import load_audio, peak_normalize
from .transition import fade_curves


def make_placeholder_bridge(
    kind: str,
    dur: float,
    sr: int = DEFAULT_SR,
    bpm: float = 120.0,
    seed: int = 0,
    gain_dbfs: float = -9.0,
) -> np.ndarray:
    """Synthesize a beat-aware bridge of length ``dur`` seconds.

    Deterministic given ``seed`` (project convention: reproducible runs).
    Returned at a modest level (``gain_dbfs``) so it sits under the mix.
    """
    rng = np.random.default_rng(seed)
    n = max(int(round(dur * sr)), 1)
    if kind == "drum_fill":
        y = _drum_fill(n, sr, bpm, rng)
    elif kind == "siren":
        y = _siren(n, sr, rng)
    elif kind == "pad":
        y = _pad(n, sr, rng)
    elif kind == "cymbal":
        y = _cymbal(n, sr, rng)
    else:  # default / "riser"
        y = _riser(n, sr, rng)
    return peak_normalize(y, target_dbfs=gain_dbfs)


def prepare_clip(
    clip: np.ndarray, sr: int, dur: float, gain_dbfs: float = -9.0
) -> np.ndarray:
    """Trim/pad ``clip`` to ``dur`` seconds and normalize — the shared seam.

    Real Colab-generated clips use this same function so the local pipeline
    treats them as static assets it only trims/normalizes/length-matches.
    """
    clip = np.asarray(clip, dtype=np.float32)
    n = int(round(dur * sr))
    if clip.size >= n:
        clip = clip[:n]
    else:
        clip = np.pad(clip, (0, n - clip.size))
    # Short fades in/out so the bridge doesn't click at its edges.
    clip = _edge_fade(clip, sr)
    return peak_normalize(clip, target_dbfs=gain_dbfs)


def beat_align_clip(clip: np.ndarray, sr: int, target_bpm: float) -> tuple[np.ndarray, float]:
    """Time-stretch a generated clip so its pulse matches ``target_bpm`` (the mix tempo).

    MusicGen doesn't honor a requested BPM precisely, so its internal beats drift
    against the transition's grid. We estimate the clip's tempo and stretch it onto
    the mix tempo (octave-folded and clamped so a bad estimate can't warp it wildly).
    Returns ``(aligned_clip, estimated_bpm)``.
    """
    clip = np.asarray(clip, dtype=np.float32)
    if target_bpm <= 0 or clip.size < sr // 2 or float(np.max(np.abs(clip))) < 1e-6:
        return clip, 0.0
    import librosa

    tempo = float(np.atleast_1d(librosa.beat.beat_track(y=clip, sr=sr)[0])[0])
    if tempo <= 0:
        return clip, 0.0
    rate = target_bpm / tempo
    # Octave-fold toward 1.0 (handles clean half-/double-time detection).
    while rate > 1.41:
        rate /= 2.0
    while rate < 0.71:
        rate *= 2.0
    # Only correct SMALL, confident tempo errors. A large residual (e.g. a 3:2
    # ratio like 94->140) means the clip just isn't at the mix tempo and MusicGen
    # ignored the BPM request — stretching it >~15% would warp it audibly and the
    # estimate is unreliable, so leave it native rather than mangle it.
    if not (0.87 <= rate <= 1.15) or abs(rate - 1.0) < 0.02:
        return clip, tempo
    from .align import apply_stretch
    return apply_stretch(clip, rate, sr=sr), tempo


# --------------------------------------------------------------------------- #
# Real AI clip: resolve / load (with procedural fallback)
# --------------------------------------------------------------------------- #
def resolve_bridge(
    overlap_sec: float,
    sr: int,
    bpm: float,
    clip_path: str | None = None,
    kind: str = "riser",
    seed: int = 0,
    gain_dbfs: float = -9.0,
) -> tuple[np.ndarray, dict]:
    """Return ``(bridge_samples, meta)`` for the tier-3 layer.

    If ``clip_path`` exists, load that real (MusicGen-Style) clip; otherwise fall
    back to the procedural stand-in. ``meta`` records the source for the sidecar.
    """
    if clip_path and os.path.exists(clip_path):
        clip, _ = load_audio(clip_path, sr=sr)
        # MusicGen ignores precise tempo, so lock the clip's pulse to the mix tempo
        # before length-matching — otherwise its beats drift off the transition grid.
        clip, clip_bpm = beat_align_clip(clip, sr, bpm)
        bridge = prepare_clip(clip, sr, overlap_sec, gain_dbfs=gain_dbfs)
        return bridge, {"source": "ai-clip", "clip_path": clip_path, "clip_bpm": clip_bpm}
    raw = make_placeholder_bridge(kind, overlap_sec, sr=sr, bpm=bpm, seed=seed,
                                  gain_dbfs=gain_dbfs)
    bridge = prepare_clip(raw, sr, overlap_sec, gain_dbfs=gain_dbfs)
    return bridge, {"source": "procedural-placeholder", "kind": kind}


# Default template (back-compat): a generic EDM riser. The genre layer passes a
# genre-authentic template from ``genre.BRIDGE_SPECS`` instead.
DEFAULT_BRIDGE_TEMPLATE = (
    "{bpm} BPM electronic transition riser{key}, smoothly building energy into a "
    "drop, atmospheric sweep and white-noise rise, no lead melody, about {dur} seconds"
)


def build_bridge_prompt(a, b, overlap_sec: float, template: str = DEFAULT_BRIDGE_TEMPLATE) -> str:
    """Fill a MusicGen text ``template`` with this transition's tempo/key/duration.

    ``template`` uses ``{bpm}``/``{key}``/``{dur}`` placeholders (see
    :data:`genre.BRIDGE_SPECS`). Encoding tempo, key and duration makes the
    generated bridge match the mix — the "text-to-audio that takes song structure
    into account" the project wants.
    """
    # The mix plays at A's tempo (B is stretched onto it), so rhythmic effects
    # (hits/buildup) should reference A's BPM to land on the beat.
    bpm = int(round(a.bpm)) if getattr(a, "bpm", 0) else int(round(getattr(b, "bpm", 120.0)))
    key = (getattr(b, "key", {}) or {}).get("name") or (getattr(a, "key", {}) or {}).get("name")
    key_str = f" in {key}" if key and key != "unknown" else ""
    effect = template.format(bpm=bpm, key=key_str, dur=f"{overlap_sec:.0f}")
    # Frame it as an ISOLATED overlay FX layered ON TOP of the transition — dry, no
    # music bed / vocals / song (so it doesn't reproduce or blend the tracks) — but
    # allow percussion/hits so buildups and impacts come through.
    return (
        f"Big punchy isolated DJ transition effect, dry and clean, no music bed, "
        f"no vocals, no song, no melody — just the effect to layer on top of a "
        f"mix: {effect}"
    )


def extract_boundary_reference(
    y_a: np.ndarray,
    y_b: np.ndarray,
    plan,
    sr: int,
    max_sec: float = 10.0,
) -> np.ndarray:
    """Build the conditioning reference for MusicGen-Style from the A->B boundary.

    Equal-power crossfade of A's tail (``region_a``) into B's head (``region_b``)
    so the reference carries the harmony/timbre of *both* tracks at the switch.
    Capped to ``max_sec`` (model context). ``y_b`` must already be tempo-stretched.
    """
    from .io import to_samples

    a0, a1 = to_samples(plan.region_a[0], sr), to_samples(plan.region_a[1], sr)
    b0, b1 = to_samples(plan.region_b[0], sr), to_samples(plan.region_b[1], sr)
    a_tail = np.asarray(y_a[a0:a1], dtype=np.float32)
    b_head = np.asarray(y_b[b0:b1], dtype=np.float32)
    n = min(len(a_tail), len(b_head), int(max_sec * sr))
    if n <= 1:
        return np.zeros(max(n, 1), dtype=np.float32)
    fade_out, fade_in = fade_curves(n, "equal_power")
    ref = a_tail[:n] * fade_out + b_head[:n] * fade_in
    return peak_normalize(ref.astype(np.float32), target_dbfs=-3.0)


# --------------------------------------------------------------------------- #
# Synthesis primitives
# --------------------------------------------------------------------------- #
def _riser(n: int, sr: int, rng: np.random.Generator) -> np.ndarray:
    """Filtered-noise swell + rising sine sweep, peaking at the end."""
    t = np.linspace(0.0, 1.0, n)
    # Amplitude swells quadratically into the drop.
    amp = t ** 2

    # Noise that brightens over time: crossfade a dull (low-passed) copy into a
    # bright (high-passed) copy so perceived "energy" rises toward the drop.
    noise = rng.standard_normal(n).astype(np.float32)
    low = _filt(noise, sr, 800.0, "low")
    high = _filt(noise, sr, 2000.0, "high")
    bright = low * (1.0 - t) + high * t
    noise_layer = bright * amp

    # Rising sine sweep (pitch glides up) layered underneath.
    f0, f1 = 200.0, 2000.0
    freq = f0 * (f1 / f0) ** t  # exponential glide
    phase = np.cumsum(2.0 * np.pi * freq / sr)
    sweep = np.sin(phase).astype(np.float32) * amp * 0.5

    return (0.7 * noise_layer + 0.3 * sweep).astype(np.float32)


def _drum_fill(n: int, sr: int, bpm: float, rng: np.random.Generator) -> np.ndarray:
    """Noise-burst hits on the beat grid, getting denser toward the end."""
    y = np.zeros(n, dtype=np.float32)
    beat_dur = 60.0 / max(bpm, 1.0)
    dur = n / sr

    # Subdivide more finely as the fill progresses: quarter -> eighth -> sixteenth.
    hits = []
    t = 0.0
    while t < dur:
        prog = t / dur if dur > 0 else 0.0
        subdiv = 1 if prog < 0.5 else (2 if prog < 0.8 else 4)
        step = beat_dur / subdiv
        hits.append(t)
        t += step

    for ht in hits:
        i = int(round(ht * sr))
        burst_len = int(0.05 * sr)
        env = np.exp(-np.linspace(0, 12, burst_len)).astype(np.float32)
        burst = rng.standard_normal(burst_len).astype(np.float32) * env
        end = min(i + burst_len, n)
        y[i:end] += burst[: end - i]
    return y


def _siren(n: int, sr: int, rng: np.random.Generator) -> np.ndarray:
    """Dub siren: a pitch-swept sine with vibrato, plus a couple of delay echoes."""
    t = np.linspace(0.0, 1.0, n)
    # Siren glides up then down over the span; vibrato gives the classic wobble.
    base = 600.0 * (3.0 ** np.sin(np.pi * t))  # ~600 Hz -> ~1.8 kHz and back
    vibrato = 1.0 + 0.06 * np.sin(2.0 * np.pi * 6.0 * t * (n / sr))
    freq = base * vibrato
    phase = np.cumsum(2.0 * np.pi * freq / sr)
    siren = np.sin(phase).astype(np.float32)
    siren *= np.minimum(1.0, t / 0.05)  # quick fade-in so it doesn't click
    # Analog-style delay throws (decaying echoes).
    y = siren.copy()
    for k, g in ((int(0.18 * sr), 0.5), (int(0.36 * sr), 0.25)):
        if 0 < k < n:
            y[k:] += g * siren[:-k]
    return y


def _pad(n: int, sr: int, rng: np.random.Generator) -> np.ndarray:
    """Ambient pad: a few detuned sine partials, slow swell, gentle low-pass wash."""
    t = np.linspace(0.0, 1.0, n)
    root = 110.0 * 2 ** (rng.integers(0, 12) / 12.0)  # random-ish root note
    y = np.zeros(n, dtype=np.float32)
    for mult, det, amp in ((1.0, 1.003, 1.0), (1.5, 0.997, 0.6), (2.0, 1.002, 0.4)):
        f = root * mult * det
        y += amp * np.sin(2.0 * np.pi * f * np.arange(n) / sr).astype(np.float32)
    # Slow swell in and out (a held, evolving wash).
    env = np.sin(np.pi * t) ** 0.5
    y = _filt(y, sr, 1800.0, "low") * env.astype(np.float32)
    return y


def _cymbal(n: int, sr: int, rng: np.random.Generator) -> np.ndarray:
    """Rock accent: one bright cymbal crash (high-passed noise, long decay) + a tom."""
    y = np.zeros(n, dtype=np.float32)
    crash = _filt(rng.standard_normal(n).astype(np.float32), sr, 3000.0, "high")
    decay = np.exp(-np.linspace(0.0, 6.0, n)).astype(np.float32)  # long shimmering tail
    y += crash * decay
    # A low tom thump right at the hit.
    tlen = min(int(0.15 * sr), n)
    tt = np.arange(tlen) / sr
    tom = np.sin(2.0 * np.pi * 90.0 * tt).astype(np.float32) * np.exp(-tt * 25.0)
    y[:tlen] += 0.7 * tom
    return y


def _filt(y: np.ndarray, sr: int, cutoff: float, btype: str, order: int = 4) -> np.ndarray:
    if y.size <= order * 3:
        return y.astype(np.float32)
    wn = np.clip(cutoff / (sr / 2.0), 1e-4, 0.99)
    sos = butter(order, wn, btype=btype, output="sos")
    return sosfiltfilt(sos, y).astype(np.float32)


def _edge_fade(y: np.ndarray, sr: int, ms: float = 10.0) -> np.ndarray:
    k = min(int(sr * ms / 1000.0), len(y) // 2)
    if k <= 0:
        return y
    ramp = np.linspace(0.0, 1.0, k, dtype=np.float32)
    y = y.copy()
    y[:k] *= ramp
    y[-k:] *= ramp[::-1]
    return y
